"use strict";

const ERROR_CODES = {
	// Auth
	USER_NOT_FOUND: "USER_NOT_FOUND",
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	OTP_EXPIRED: "OTP_EXPIRED",
	OTP_INVALID: "OTP_INVALID",
	TOKEN_EXPIRED: "TOKEN_EXPIRED",
	TOKEN_INVALID: "TOKEN_INVALID",
	EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
	EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",
	// Booking
	BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
	INVALID_BOOKING_TRANSITION: "INVALID_BOOKING_TRANSITION",
	PACKAGE_UNAVAILABLE: "PACKAGE_UNAVAILABLE",
	PACKAGE_NOT_FOUND: "PACKAGE_NOT_FOUND",
	INSUFFICIENT_CAPACITY: "INSUFFICIENT_CAPACITY",
	// Payment
	PAYMENT_FAILED: "PAYMENT_FAILED",
	PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
	PAYMENT_ALREADY_VERIFIED: "PAYMENT_ALREADY_VERIFIED",
	COMMITMENT_FEE_REQUIRED: "COMMITMENT_FEE_REQUIRED",
	MILESTONE_NOT_FOUND: "MILESTONE_NOT_FOUND",
	MILESTONE_ALREADY_PAID: "MILESTONE_ALREADY_PAID",
	// Quote
	QUOTE_NOT_FOUND: "QUOTE_NOT_FOUND",
	QUOTE_EXPIRED: "QUOTE_EXPIRED",
	QUOTE_ALREADY_RESPONDED: "QUOTE_ALREADY_RESPONDED",
	SLA_BREACHED: "SLA_BREACHED",
	// Contract
	CONTRACT_NOT_FOUND: "CONTRACT_NOT_FOUND",
	CONTRACT_NOT_ACCEPTED: "CONTRACT_NOT_ACCEPTED",
	CONTRACT_ALREADY_ACCEPTED: "CONTRACT_ALREADY_ACCEPTED",
	TEMPLATE_NOT_FOUND: "TEMPLATE_NOT_FOUND",
	// Partner
	PARTNER_NOT_FOUND: "PARTNER_NOT_FOUND",
	INVENTORY_UNAVAILABLE: "INVENTORY_UNAVAILABLE",
	DESTINATION_NOT_FOUND: "DESTINATION_NOT_FOUND",
	// Tour
	TOUR_REQUEST_NOT_FOUND: "TOUR_REQUEST_NOT_FOUND",
	INTEREST_NOT_FOUND: "INTEREST_NOT_FOUND",
	// Notification
	NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",
	NOTIFICATION_ACCESS_DENIED: "NOTIFICATION_ACCESS_DENIED",
	// Media
	UPLOAD_FAILED: "UPLOAD_FAILED",
	DELETE_FAILED: "DELETE_FAILED",
	// Organization
	ORG_NOT_FOUND: "ORG_NOT_FOUND",
	ORG_SLUG_EXISTS: "ORG_SLUG_EXISTS",
	ORG_ALREADY_ACTIVE: "ORG_ALREADY_ACTIVE",
	ORG_ALREADY_SUSPENDED: "ORG_ALREADY_SUSPENDED",
	// Review
	REVIEW_NOT_FOUND: "REVIEW_NOT_FOUND",
	REVIEW_ACCESS_DENIED: "REVIEW_ACCESS_DENIED",
	// Subscriber
	SUBSCRIBER_ALREADY_EXISTS: "SUBSCRIBER_ALREADY_EXISTS",
	// CMS
	CMS_NOT_CONFIGURED: "CMS_NOT_CONFIGURED",
	CMS_QUERY_FAILED: "CMS_QUERY_FAILED",
	// Waitlist
	WAITLIST_FULL: "WAITLIST_FULL",
	WAITLIST_NOT_FOUND: "WAITLIST_NOT_FOUND",
	BOOKING_CUTOFF_PASSED: "BOOKING_CUTOFF_PASSED",
	// General
	VALIDATION_ERROR: "VALIDATION_ERROR",
	NOT_FOUND: "NOT_FOUND",
	INTERNAL_ERROR: "INTERNAL_ERROR",
};

const BOOKING_STATUSES = {
	PENDING_PARTNER_CONFIRMATION: "pending_partner_confirmation",
	PENDING_PAYMENT: "pending_payment",
	PAYMENT_PROCESSING: "payment_processing",
	CONFIRMED: "confirmed",
	CANCELLED: "cancelled",
	CANCELLED_WITH_REFUND: "cancelled_with_refund",
	TOUR_SCHEDULED: "tour_scheduled",
	TOUR_IN_PROGRESS: "tour_in_progress",
	TOUR_COMPLETED: "tour_completed",
	REVIEW_REQUESTED: "review_requested",
};

const TOUR_REQUEST_STATUSES = {
	DRAFT: "draft",
	SUBMITTED: "submitted_for_pricing",
	IN_QUEUE: "in_pricing_queue",
	ASSIGNED: "assigned_to_staff",
	QUOTE_SENT: "quote_sent",
	QUOTE_ACCEPTED: "quote_accepted",
	QUOTE_REJECTED: "quote_rejected",
	QUOTE_EXPIRED: "quote_expired",
	CANCELLED: "cancelled",
};

const QUOTE_STATUSES = {
	PENDING: "pending",
	CALCULATING: "calculating",
	SENT: "sent",
	ACCEPTED: "accepted",
	REJECTED: "rejected",
	EXPIRED: "expired",
	REVISED: "revised",
};

const PAYMENT_STATUSES = {
	PENDING: "pending",
	PROCESSING: "processing",
	SUCCESS: "success",
	FAILED: "failed",
	REFUNDED: "refunded",
	PARTIALLY_REFUNDED: "partially_refunded",
};

const CONTRACT_STATUSES = {
	DRAFT: "draft",
	SENT: "sent",
	ACCEPTED: "accepted",
	REJECTED: "rejected",
	EXPIRED: "expired",
};

const PAYMENT_PLAN_STATUSES = {
	ACTIVE: "active",
	COMPLETED: "completed",
	DEFAULTED: "defaulted",
	CANCELLED: "cancelled",
};

const MILESTONE_STATUSES = {
	PENDING: "pending",
	OVERDUE: "overdue",
	PAID: "paid",
	WAIVED: "waived",
};

const INTEREST_STATUSES = {
	ACTIVE: "active",
	CONVERTED: "converted_to_booking",
	WITHDRAWN: "withdrawn",
	EXPIRED: "expired",
};

const USER_ROLES = {
	CUSTOMER: "customer",
	STAFF: "staff",
	ADMIN: "admin",
	SUPER_ADMIN: "super_admin",
};

const ORG_STATUSES = {
	ACTIVE: "active",
	SUSPENDED: "suspended",
	TRIAL: "trial",
};

const SUBSCRIPTION_PLANS = {
	FREE: "free",
	BASIC: "basic",
	PROFESSIONAL: "professional",
	ENTERPRISE: "enterprise",
};

const NOTIFICATION_CHANNELS = {
	EMAIL: "email",
	SMS: "sms",
	WHATSAPP: "whatsapp",
	IN_APP: "in_app",
};

const PARTNER_INVENTORY_MODELS = {
	ON_REQUEST: "on_request",
	FREE_SALE: "free_sale",
	ALLOTMENT: "allotment",
};

const HOTEL_TIERS = {
	BUDGET: "budget",
	STANDARD: "standard",
	PREMIUM: "premium",
	LUXURY: "luxury",
};

const TRANSPORT_TYPES = {
	BUS: "bus",
	MINIBUS: "minibus",
	SUV: "suv",
	SEDAN: "sedan",
	VAN: "van",
};

const SELLING_MODES = {
	GROUP_BUY: "group_buy",
	INDIVIDUAL_SEATS: "individual_seats",
};

const WAITLIST_STATUSES = {
	WAITING: "waiting",
	OFFERED: "offered",
	ACCEPTED: "accepted",
	EXPIRED: "expired",
	CANCELLED: "cancelled",
};

module.exports = {
	ERROR_CODES,
	BOOKING_STATUSES,
	TOUR_REQUEST_STATUSES,
	QUOTE_STATUSES,
	PAYMENT_STATUSES,
	CONTRACT_STATUSES,
	PAYMENT_PLAN_STATUSES,
	MILESTONE_STATUSES,
	INTEREST_STATUSES,
	USER_ROLES,
	NOTIFICATION_CHANNELS,
	PARTNER_INVENTORY_MODELS,
	HOTEL_TIERS,
	TRANSPORT_TYPES,
	SELLING_MODES,
	WAITLIST_STATUSES,
	ORG_STATUSES,
	SUBSCRIPTION_PLANS,
};
