"use strict";

require("dotenv").config();

const dns = require("dns");
dns.setServers(["8.8.8.8", "1.1.1.1"]);
const mongoose = require("mongoose");
const slugify = require("slugify");

const MONGO_URI = process.env.MONGO_URI;
if (!MONGO_URI) {
  console.error("ERROR: MONGO_URI is not set in .env");
  process.exit(1);
}

// ── Minimal schemas (seed-only — not the full app models) ─────────────────────
const DestinationSchema = new mongoose.Schema(
  {
    name:           { type: String, required: true, unique: true, trim: true },
    slug:           { type: String, unique: true, lowercase: true },
    region:         { type: String, required: true },
    country:        { type: String, required: true, default: "Ghana" },
    description:    { type: String },
    subtitle:       { type: String },
    coverImage:     { type: String },
    images:         { type: [String], default: [] },
    highlights:     { type: [String], default: [] },
    bestTimeToVisit:{ type: String },
    weather:        { avgTemp: Number, rainyMonths: [String], bestMonths: [String] },
    isActive:       { type: Boolean, default: true },
  },
  { timestamps: true, collection: "destinations" }
);

const TourPackageSchema = new mongoose.Schema(
  {
    title:          { type: String, required: true, trim: true },
    slug:           { type: String, unique: true, lowercase: true },
    description:    { type: String },
    destinationId:  { type: mongoose.Schema.Types.ObjectId, ref: "Destination", required: true },
    country:        { type: String },
    durationDays:   { type: Number, required: true },
    basePrice:      { type: Number },
    displayCurrency:{ type: String, default: "GHS" },
    images:         { type: [String], default: [] },
    coverImage:     { type: String },
    heroImages:     { type: [String], default: [] },
    heroMainImage:  { type: String },
    rating:         { type: Number, default: 0, min: 0, max: 5 },
    reviewCount:    { type: Number, default: 0 },
    tags:           { type: [String], default: [] },
    tourType:       { type: String, enum: ["day_tour", "multi_day", "express"], default: "multi_day" },
    category:       { type: String, enum: ["leisure", "business", "ekolure"] },
    difficulty:     { type: String, enum: ["easy", "moderate", "challenging"], default: "easy" },
    bestFor:        { type: [String], default: [] },
    highlights:     { type: [String], default: [] },
    inclusions:     { type: [String], default: [] },
    exclusions:     { type: [String], default: [] },
    itinerary: [{
      day:         { type: Number },
      title:       { type: String },
      description: { type: String },
      activities:  [{ time: String, activity: String, tag: String }],
    }],
    sellingMode:    { type: String, default: "group_buy" },
    totalCapacity:  { type: Number },
    remainingCapacity: { type: Number },
    isActive:       { type: Boolean, default: true },
    status:         { type: String, enum: ["draft", "published", "archived"], default: "published" },
    featured:       { type: Boolean, default: false },
    languages:      { type: [String], default: ["English"] },
    transportType:  { type: String },
    pickupIncluded: { type: Boolean, default: false },
    minAge:         { type: Number },
    cancellationPolicy: { type: String },
  },
  { timestamps: true, collection: "tourpackages" }
);

// ── Tour data ──────────────────────────────────────────────────────────────────
// Images: Unsplash CDN (no API key required for display).
// basePrice: GHS for Ghana tours, USD for all others (displayCurrency set accordingly).
// country: lowercase — matches tourPackage.service.js query.country = country.toLowerCase()

const tours = [

  // ════════════════════════════════════════════════════════════════════════════
  // GHANA
  // ════════════════════════════════════════════════════════════════════════════

  {
    title: "Cape Coast Heritage & Slave Castles Expedition",
    country: "ghana",
    destinationName: "Cape Coast",
    destinationRegion: "Central Region",
    destinationCountry: "Ghana",
    durationDays: 2,
    basePrice: 1450,
    displayCurrency: "GHS",
    tourType: "multi_day",
    category: "leisure",
    difficulty: "easy",
    rating: 4.9,
    reviewCount: 147,
    featured: true,
    bestFor: ["Diaspora visitors", "History enthusiasts", "Couples", "Educational groups"],
    tags: ["Heritage", "History", "UNESCO", "Culture", "Diaspora"],
    languages: ["English"],
    pickupIncluded: true,
    pickupLocation: "Accra (hotel pickup)",
    totalCapacity: 16,
    remainingCapacity: 16,
    cancellationPolicy: "Free cancellation up to 48 hours before departure.",
    description: "Journey through the haunting legacy of the transatlantic slave trade at Cape Coast Castle and Elmina Castle — two UNESCO World Heritage Sites on Ghana's Central Coast. Walk the same dungeons where millions of enslaved Africans were held before passing through the Door of No Return, and pay respects at the Assin Manso Slave River memorial. A deeply moving and educational experience that connects the African diaspora to its roots.",
    highlights: [
      "Guided tour of Cape Coast Castle — dungeons, cannons, and the Door of No Return",
      "Visit Elmina Castle, the oldest European building in sub-Saharan Africa (built 1482)",
      "Assin Manso Slave River site — the last bathing point before embarkation",
      "West African Historical Museum inside Cape Coast Castle",
      "Canopy walkway at Kakum National Park above 30m tropical rainforest",
      "Sunset stroll along Cape Coast beach with local fishing boats",
    ],
    inclusions: [
      "Return private AC transport from Accra",
      "All entrance fees (Cape Coast Castle, Elmina Castle, Kakum National Park)",
      "Licensed GCAA tour guide (2 days)",
      "1 night accommodation (3-star guesthouse, twin/double room)",
      "Day 1 dinner and Day 2 breakfast",
      "Bottled water throughout",
    ],
    exclusions: [
      "International flights",
      "Personal travel insurance",
      "Souvenirs and personal shopping",
      "Meals not listed",
    ],
    itinerary: [
      {
        day: 1,
        title: "Accra Departure & Cape Coast Castle",
        description: "Depart Accra early morning by private AC vehicle (3 hr drive). Guided tour of Cape Coast Castle including dungeons and Door of No Return. Afternoon visit to Elmina Castle. Evening dinner at a beachfront restaurant.",
        activities: [
          { activity: "Depart Accra — private AC vehicle (3 hr drive)" },
          { activity: "Arrive Cape Coast — check in and freshen up" },
          { activity: "Guided tour of Cape Coast Castle including dungeons and Door of No Return" },
          { activity: "Lunch at a local Cape Coast chop bar — jollof rice, grilled tilapia" },
          { activity: "Afternoon visit to Elmina Castle (15 min drive)" },
          { activity: "Evening at leisure — dinner at beachfront restaurant" },
        ],
      },
      {
        day: 2,
        title: "Assin Manso & Kakum Canopy Walk",
        description: "Morning drive to Assin Manso Slave River memorial. Reflection ceremony and guided history talk. Drive to Kakum National Park for the iconic canopy walkway experience above the forest.",
        activities: [
          { activity: "Morning drive to Assin Manso Slave River memorial" },
          { activity: "Reflection ceremony and guided history talk" },
          { activity: "Drive to Kakum National Park" },
          { activity: "Canopy walkway experience above the forest canopy" },
          { activity: "Depart Cape Coast and return to Accra" },
        ],
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1580502304784-8985b7eb7260?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1523952578875-e6bb18b26645?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1464419014442-769c523d575b?w=1200&q=80&auto=format&fit=crop",
    ],
  },

  {
    title: "Ashanti Kingdom & Kente Culture Deep Dive",
    country: "ghana",
    destinationName: "Kumasi",
    destinationRegion: "Ashanti Region",
    destinationCountry: "Ghana",
    durationDays: 3,
    basePrice: 2200,
    displayCurrency: "GHS",
    tourType: "multi_day",
    category: "leisure",
    difficulty: "easy",
    rating: 4.8,
    reviewCount: 112,
    featured: true,
    bestFor: ["Culture lovers", "Families", "Couples", "Photography enthusiasts", "Diaspora visitors"],
    tags: ["Culture", "Heritage", "Craft", "Royalty", "Local Life", "Food"],
    languages: ["English"],
    pickupIncluded: true,
    pickupLocation: "Accra (hotel pickup)",
    totalCapacity: 12,
    remainingCapacity: 12,
    cancellationPolicy: "Free cancellation up to 48 hours before departure.",
    description: "Immerse yourself in the living culture of the Ashanti Kingdom — Ghana's most powerful pre-colonial empire — in Kumasi, the Garden City of West Africa. Visit the Manhyia Palace, watch master weavers create Kente cloth on traditional looms, and explore Kejetia Market, one of the largest open-air markets in West Africa. A traditional Ashanti naming ceremony crowns this authentic cultural journey.",
    highlights: [
      "Manhyia Palace Museum — seat of the Asantehene, Ghana's most powerful traditional ruler",
      "Bonwire Kente Weaving Village — watch artisans weave elaborate ceremonial cloth on traditional looms",
      "Kejetia Central Market — a sprawling maze of over 10,000 stalls",
      "Traditional Ashanti naming ceremony (you receive a Ghanaian name based on your birth day)",
      "Okomfo Anokye Sword site — legendary sword that has remained in the ground since the 1700s",
      "Lake Bosomtwe — Ghana's only natural lake, sacred to the Ashanti people",
    ],
    inclusions: [
      "Return private AC transport from Accra",
      "All entrance fees and ceremony fees",
      "Licensed cultural guide (3 days)",
      "2 nights accommodation (3-star hotel, Kumasi)",
      "Day 1 dinner, Day 2 breakfast & dinner, Day 3 breakfast and lunch",
      "Kente cloth keepsake from Bonwire",
    ],
    exclusions: [
      "Domestic flight upgrade (if chosen)",
      "International flights",
      "Personal purchases at markets",
      "Travel insurance",
    ],
    itinerary: [
      {
        day: 1,
        title: "Accra to Kumasi — Arrival & Kejetia Market",
        description: "Depart Accra by private vehicle (5 hr drive). Afternoon exploration of Kejetia Central Market with local guide. Visit Prempeh II Jubilee Museum for an introduction to Ashanti history.",
        activities: [
          { activity: "Depart Accra by private vehicle (5 hr drive)" },
          { activity: "Check in to hotel in Kumasi" },
          { activity: "Afternoon exploration of Kejetia Central Market with local guide" },
          { activity: "Visit Prempeh II Jubilee Museum" },
          { activity: "Welcome dinner — Ashanti cuisine (fufu and light soup)" },
        ],
      },
      {
        day: 2,
        title: "Manhyia Palace, Bonwire & Naming Ceremony",
        description: "Morning guided tour of Manhyia Palace Museum. Drive to Bonwire village to witness Kente weaving on traditional looms. Traditional Ashanti naming ceremony with village elders.",
        activities: [
          { activity: "Morning guided tour of Manhyia Palace Museum" },
          { activity: "Drive to Bonwire — witness Kente weaving on traditional looms" },
          { activity: "Traditional Ashanti naming ceremony with village elders" },
          { activity: "Visit Adanwomase — birthplace of Kente weaving, try weaving yourself" },
          { activity: "Evening cultural performance — drumming and Adowa dance" },
        ],
      },
      {
        day: 3,
        title: "Okomfo Anokye, Lake Bosomtwe & Departure",
        description: "Visit Okomfo Anokye Sword site. Drive to Lake Bosomtwe for a boat ride and swim. Return to Kumasi and depart for Accra.",
        activities: [
          { activity: "Visit Okomfo Anokye Sword site" },
          { activity: "Drive to Lake Bosomtwe — sacred crater lake, boat ride and swim" },
          { activity: "Lunch at lakeside restaurant" },
          { activity: "Return to Kumasi and depart for Accra" },
        ],
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1614005157364-67894d3dc531?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560851691-ebb64b584d3d?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1519830103773-4bdc5166a0db?w=1200&q=80&auto=format&fit=crop",
    ],
  },

  {
    title: "Mole National Park Big Five Safari",
    country: "ghana",
    destinationName: "Mole National Park",
    destinationRegion: "Savannah Region",
    destinationCountry: "Ghana",
    durationDays: 4,
    basePrice: 5800,
    displayCurrency: "GHS",
    tourType: "multi_day",
    category: "ekolure",
    difficulty: "moderate",
    rating: 4.7,
    reviewCount: 89,
    featured: true,
    bestFor: ["Wildlife enthusiasts", "Photography lovers", "Couples", "Adventure travelers", "Birdwatchers"],
    tags: ["Safari", "Wildlife", "Nature", "Adventure", "Photography", "Birds"],
    languages: ["English"],
    pickupIncluded: true,
    pickupLocation: "Accra (Kotoka Airport)",
    totalCapacity: 10,
    remainingCapacity: 10,
    cancellationPolicy: "Free cancellation up to 72 hours before departure.",
    description: "Escape to Ghana's largest wildlife reserve — a 4,800 sq km expanse of Guinea savannah in the Savannah Region — for an authentic African safari. Mole National Park is home to over 90 mammal species including elephants, hippos, warthogs, and buffalo, plus 300+ bird species. Morning game drives and walking safaris with armed rangers bring you face-to-face with wildlife in a raw, uncrowded setting.",
    highlights: [
      "Morning and sunset 4×4 game drives spotting elephants, warthogs, kob antelope, and baboons",
      "Walking safari with armed ranger — the most intimate wildlife encounter in Ghana",
      "Hippo pool observation at the Mole watering hole",
      "Visit to Larabanga — home of Ghana's oldest mosque (15th-century mud-and-stick architecture)",
      "300+ bird species including ground hornbills, sunbirds, and raptors",
      "Stargazing from Mole Motel's iconic poolside overlooking the watering hole",
    ],
    inclusions: [
      "Return domestic flights Accra–Tamale",
      "All transfers (Tamale to Mole and return)",
      "3 nights accommodation at Mole Motel (double/twin rooms)",
      "4 game drives (2×4WD vehicle, 2×walking safari with ranger)",
      "Park entrance fees for 3 days",
      "All meals (3 breakfasts, 3 lunches, 3 dinners)",
      "Professional naturalist guide throughout",
      "Bottled water and bush sundowner drinks",
    ],
    exclusions: [
      "International flights to Ghana",
      "Travel insurance",
      "Alcoholic beverages beyond sundowners",
      "Personal items and tips",
    ],
    itinerary: [
      {
        day: 1,
        title: "Accra to Tamale — Northern Gateway Arrival",
        description: "Early morning domestic flight from Accra to Tamale (45 min). Meet driver and depart for Mole (approx. 3 hr drive through savannah). Late afternoon sunset game drive by 4×4.",
        activities: [
          { activity: "Early morning domestic flight from Accra to Tamale (45 min)" },
          { activity: "Meet driver and depart for Mole (approx. 3 hr drive through savannah)" },
          { activity: "Check in to Mole Motel — poolside rooms overlooking watering hole" },
          { activity: "Late afternoon sunset game drive by 4×4" },
          { activity: "Elephant sighting at the watering hole at dusk" },
        ],
      },
      {
        day: 2,
        title: "Full Day Safari — Game Drives & Walking Safari",
        description: "Pre-dawn 5:30am walking safari with armed ranger tracking elephant herds through scrub woodland. Afternoon 4×4 game drive to the hippo pool. Sundowner drinks at the pool.",
        activities: [
          { activity: "Pre-dawn 5:30am walking safari with armed ranger" },
          { activity: "Track elephant herds on foot through scrub woodland" },
          { activity: "Return for breakfast, rest during midday heat" },
          { activity: "Afternoon 4×4 game drive — hippo pool, kob antelope, baboons" },
          { activity: "Sundowner drinks at the pool overlooking the watering hole" },
        ],
      },
      {
        day: 3,
        title: "Larabanga Mosque & Cultural Village",
        description: "Morning game drive then drive to Larabanga to visit Ghana's oldest mosque and do a village walk with a local guide. Final afternoon game drive.",
        activities: [
          { activity: "Morning game drive — second chance for elephant encounters" },
          { activity: "Drive to Larabanga (30 min) — visit Ghana's oldest mosque" },
          { activity: "Local village walk with Larabanga community guide" },
          { activity: "Return to Mole for final afternoon game drive" },
          { activity: "Farewell dinner under the stars" },
        ],
      },
      {
        day: 4,
        title: "Final Morning Safari & Return to Accra",
        description: "Final 6am game drive then return to Tamale airport for the flight back to Accra.",
        activities: [
          { activity: "Final 6am game drive" },
          { activity: "Breakfast and check out" },
          { activity: "Drive to Tamale airport" },
          { activity: "Fly back to Accra" },
        ],
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1560118386-f35cf6a0791d?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1577900190299-7316c32fe85f?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1614005157364-67894d3dc531?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1716998462026-66dbe5c97af3?w=1200&q=80&auto=format&fit=crop",
    ],
  },

  {
    title: "Volta Region Waterfalls & Canopy Escape",
    country: "ghana",
    destinationName: "Hohoe",
    destinationRegion: "Volta Region",
    destinationCountry: "Ghana",
    durationDays: 3,
    basePrice: 1850,
    displayCurrency: "GHS",
    tourType: "multi_day",
    category: "ekolure",
    difficulty: "moderate",
    rating: 4.6,
    reviewCount: 78,
    bestFor: ["Hikers", "Nature lovers", "Adventure couples", "Solo travelers", "Eco-tourists"],
    tags: ["Nature", "Adventure", "Hiking", "Eco-tourism", "Wildlife", "Waterfall"],
    languages: ["English"],
    pickupIncluded: true,
    pickupLocation: "Accra (hotel pickup)",
    totalCapacity: 14,
    remainingCapacity: 14,
    cancellationPolicy: "Free cancellation up to 48 hours before departure.",
    description: "Trek to Wli Waterfalls — the tallest waterfall in West Africa — nestled inside the Agumatsa Wildlife Sanctuary near the Ghana–Togo border. Combined with a visit to Tafi Atome Monkey Sanctuary, home to sacred Mona monkeys that local communities have protected for centuries, this is an unforgettable eco-escape through the Volta highlands.",
    highlights: [
      "Wli (Agumatsa) Waterfalls — tallest waterfall in West Africa, thundering 80m into a natural pool",
      "Hike through Agumatsa Wildlife Sanctuary with 200+ bird species",
      "Tafi Atome Monkey Sanctuary — feed sacred Mona monkeys by hand",
      "Tafi-Mador Kente weaving village — traditional cloth-making demonstration",
      "8 river bridge crossings on the trail to the lower falls",
      "Panoramic views from the Hohoe highlands over the Volta plains",
    ],
    inclusions: [
      "Return private AC transport from Accra",
      "All entrance fees (Wli Falls, Agumatsa Sanctuary, Tafi Atome)",
      "Licensed eco-guide (3 days)",
      "2 nights guesthouse accommodation (en-suite rooms)",
      "All meals (2 breakfasts, 2 lunches, 2 dinners)",
      "Rain poncho and trekking poles",
      "Bottled water",
    ],
    exclusions: [
      "Upper falls guide fee (optional, GHS 80 extra)",
      "International flights",
      "Travel insurance",
    ],
    itinerary: [
      {
        day: 1,
        title: "Accra to Hohoe — Volta Highlands Arrival",
        description: "Depart Accra at 6am by private AC vehicle (4.5 hr drive through Volta Region). Check in to guesthouse in Hohoe. Afternoon orientation walk.",
        activities: [
          { activity: "Depart Accra at 6am — private AC vehicle (4.5 hr drive)" },
          { activity: "Scenic drive through Volta Region with roadside stop" },
          { activity: "Check in to guesthouse in Hohoe" },
          { activity: "Afternoon orientation walk around Hohoe town" },
          { activity: "Dinner — banku and okra stew at local chop bar" },
        ],
      },
      {
        day: 2,
        title: "Wli Waterfalls Trek & Agumatsa Sanctuary",
        description: "Drive to Wli village and trek to the lower waterfalls through 8 river bridge crossings. Swim in the natural pool at the base of the falls.",
        activities: [
          { activity: "Early morning drive to Wli village (45 min)" },
          { activity: "Trek to lower Wli Waterfalls — 1.5 hr trail with 8 river bridge crossings" },
          { activity: "Swim in the natural pool at the base of the falls" },
          { activity: "Optional: Upper falls hike (4 hrs, challenging)" },
          { activity: "Packed lunch by the falls" },
        ],
      },
      {
        day: 3,
        title: "Tafi Monkey Sanctuary & Kente Village",
        description: "Morning at Tafi Atome Monkey Sanctuary where you can hand-feed the sacred Mona monkeys. Visit Tafi-Mador village for a Kente weaving demonstration before returning to Accra.",
        activities: [
          { activity: "Morning drive to Tafi Atome Monkey Sanctuary" },
          { activity: "Guided walk — hand-feed Mona monkeys" },
          { activity: "Visit Tafi-Mador village for Kente weaving demonstration" },
          { activity: "Depart Volta Region and return to Accra" },
        ],
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1519830103773-4bdc5166a0db?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1523952578875-e6bb18b26645?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1464419014442-769c523d575b?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1610805177214-885738d255f1?w=1200&q=80&auto=format&fit=crop",
    ],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // NIGERIA
  // ════════════════════════════════════════════════════════════════════════════

  {
    title: "Lagos Pulse — City, Art & Afrobeats Experience",
    country: "nigeria",
    destinationName: "Lagos",
    destinationRegion: "Lagos State",
    destinationCountry: "Nigeria",
    durationDays: 2,
    basePrice: 115,
    displayCurrency: "USD",
    tourType: "multi_day",
    category: "leisure",
    difficulty: "easy",
    rating: 4.5,
    reviewCount: 203,
    featured: true,
    bestFor: ["Art lovers", "Music fans", "First-time Nigeria visitors", "Couples", "Young professionals"],
    tags: ["City", "Culture", "Art", "Music", "Food", "Urban", "Afrobeats"],
    languages: ["English"],
    pickupIncluded: true,
    pickupLocation: "Lagos hotel pickup",
    totalCapacity: 12,
    remainingCapacity: 12,
    cancellationPolicy: "Free cancellation up to 48 hours before departure.",
    description: "Dive into Africa's most electric megacity — a coastal metropolis of 25 million people where traditional Yoruba culture collides with global finance and world-class contemporary art. From the floating stilt village of Makoko to Nike Art Gallery's five floors of Nigerian masterpieces, and from the Afrika Shrine to the longest canopy walk in Africa at Lekki Conservation Centre, Lagos defies expectation at every turn.",
    highlights: [
      "Nike Art Gallery — five-story gallery housing 8,000 works by Nigerian artists",
      "Makoko Floating Village — guided boat ride through Lagos's iconic stilt community",
      "Afrika Shrine — legendary music venue and cultural space of Fela Kuti",
      "Lekki Conservation Centre — 78-hectare urban wetland with Africa's longest canopy walk",
      "Lekki Arts & Crafts Market — handmade masks, Yoruba beadwork, and batik fabric",
      "Lagos Island & Balogun Market — the commercial and historical heart of the city",
    ],
    inclusions: [
      "Private AC vehicle with driver (2 days)",
      "Licensed Lagos city guide (2 days)",
      "All entrance fees (National Museum, Makoko boat, Lekki Conservation Centre, Nike Gallery)",
      "Day 1 lunch and Day 2 lunch",
      "Bottled water throughout",
    ],
    exclusions: [
      "Hotel accommodation",
      "Dinners",
      "Afrika Shrine cover charge (approx. NGN 2,000 — optional)",
      "Personal shopping at markets",
      "International flights",
      "Travel insurance",
    ],
    itinerary: [
      {
        day: 1,
        title: "Lagos Island, Makoko & Nike Art Gallery",
        description: "Lagos Island historical sites and Balogun Market walk. Boat tour of Makoko Floating Village. Afternoon at Nike Art Gallery, Victoria Island.",
        activities: [
          { activity: "Hotel pickup — private AC vehicle with local guide" },
          { activity: "Lagos Island — Tinubu Square, National Museum of Nigeria" },
          { activity: "Balogun Market walk with guide" },
          { activity: "Boat tour of Makoko Floating Village (45 min)" },
          { activity: "Lunch on Lagos Island — suya, jollof rice, egusi soup" },
          { activity: "Afternoon: Nike Art Gallery, Victoria Island (3–4 hours)" },
        ],
      },
      {
        day: 2,
        title: "Lekki Canopy Walk, Craft Market & Afrika Shrine",
        description: "Morning at Lekki Conservation Centre for Africa's longest canopy walk. Lekki Arts & Crafts Market. Optional evening at the Afrika Shrine for live Afrobeats.",
        activities: [
          { activity: "Morning: Lekki Conservation Centre — 401m suspended canopy walk" },
          { activity: "Wildlife spotting — monkeys, monitor lizards, crocodiles, birds" },
          { activity: "Lekki Arts & Crafts Market — authentic souvenirs" },
          { activity: "Lunch in Lekki" },
          { activity: "Afternoon: Freedom Park — historic colonial jail turned arts venue" },
          { activity: "Evening (optional): Afrika Shrine for live Afrobeats (Tues/Thurs/Sat)" },
        ],
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1618828665011-0abd973f7bb8?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1559833064-6f4573ec1ac9?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1569706971306-de5d78f6418e?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1594538756542-8c88bda491c5?w=1200&q=80&auto=format&fit=crop",
    ],
  },

  {
    title: "Osun-Osogbo Sacred Grove — Yoruba Spiritual Journey",
    country: "nigeria",
    destinationName: "Osogbo",
    destinationRegion: "Osun State",
    destinationCountry: "Nigeria",
    durationDays: 2,
    basePrice: 90,
    displayCurrency: "USD",
    tourType: "multi_day",
    category: "leisure",
    difficulty: "easy",
    rating: 4.7,
    reviewCount: 94,
    bestFor: ["Spiritual seekers", "History enthusiasts", "Art lovers", "Solo travelers", "Diaspora visitors"],
    tags: ["Spiritual", "UNESCO", "Yoruba", "Heritage", "Culture", "Art"],
    languages: ["English"],
    pickupIncluded: true,
    pickupLocation: "Lagos (hotel pickup)",
    totalCapacity: 12,
    remainingCapacity: 12,
    cancellationPolicy: "Free cancellation up to 48 hours before departure.",
    description: "Step inside one of the last remaining sacred groves of the Yoruba people — a 75-hectare forest sanctuary along the Osun River inscribed as a UNESCO World Heritage Site in 2005. This living spiritual landscape holds 40 shrines and sacred altars dedicated to Osun (goddess of fertility and fresh water). Combined with a stop at Ile-Ife museum — the cradle of Yoruba civilization — this is a rare encounter with living West African religion and art.",
    highlights: [
      "Osun-Osogbo Sacred Grove — UNESCO-listed forest sanctuary with 40 shrines and sculptures",
      "Osun River ritual site — Nigeria's most sacred river for Yoruba pilgrims",
      "Sculptures by Susanne Wenger — Austrian artist who devoted her life to the grove's restoration",
      "Ile-Ife National Museum — Ife bronze heads and terracotta sculptures (11th–15th century)",
      "Osun Craft Village — tie-dye, woodcarving, and traditional drum-making workshops",
      "Optional: Osun-Osogbo Festival attendance (August only)",
    ],
    inclusions: [
      "Return private AC transport from Lagos",
      "Licensed Yoruba cultural guide (2 days)",
      "All entrance fees (Sacred Grove, Ile-Ife Museum)",
      "1 night accommodation (3-star hotel, Osogbo)",
      "Day 1 dinner and Day 2 breakfast",
      "Bottled water throughout",
    ],
    exclusions: [
      "International flights",
      "Personal purchases at craft village",
      "Drumming class fee (optional)",
      "Travel insurance",
    ],
    itinerary: [
      {
        day: 1,
        title: "Lagos to Osogbo — Arrival & Sacred Grove",
        description: "Depart Lagos or Ibadan by private vehicle (2.5–4 hr drive). Afternoon guided tour of Osun-Osogbo Sacred Grove. Walk the river path past ancient shrines and sacred sculptures.",
        activities: [
          { activity: "Depart Lagos — private vehicle (2.5–4 hr drive)" },
          { activity: "Check in to hotel in Osogbo" },
          { activity: "Afternoon guided tour of Osun-Osogbo Sacred Grove" },
          { activity: "Walk the river path past 40 ancient shrines and sacred sculptures" },
          { activity: "Sunset reflection by the Osun River" },
          { activity: "Dinner — pounded yam, egusi soup, bush meat" },
        ],
      },
      {
        day: 2,
        title: "Craft Village, Ile-Ife & Return",
        description: "Morning at Osun Craft Village for tie-dye and woodcarving. Drive to Ile-Ife for the National Museum and Ooni Palace.",
        activities: [
          { activity: "Morning visit to Osun Craft Village — adire (tie-dye) and woodcarving" },
          { activity: "Optional drumming class" },
          { activity: "Drive to Ile-Ife (45 min) — National Museum and Ooni Palace" },
          { activity: "Ile-Ife bronze heads and Yoruba royal artifacts" },
          { activity: "Return to Lagos" },
        ],
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1615027212409-2628cc0cc11a?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1519830103773-4bdc5166a0db?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1464419014442-769c523d575b?w=1200&q=80&auto=format&fit=crop",
    ],
  },

  {
    title: "Yankari Game Reserve — Nigeria's Wild North",
    country: "nigeria",
    destinationName: "Yankari National Park",
    destinationRegion: "Bauchi State",
    destinationCountry: "Nigeria",
    durationDays: 4,
    basePrice: 260,
    displayCurrency: "USD",
    tourType: "multi_day",
    category: "ekolure",
    difficulty: "moderate",
    rating: 4.6,
    reviewCount: 67,
    bestFor: ["Wildlife enthusiasts", "Adventure travelers", "Couples", "Photography lovers", "Birdwatchers"],
    tags: ["Safari", "Wildlife", "Nature", "Adventure", "Birds", "Swimming"],
    languages: ["English"],
    pickupIncluded: true,
    pickupLocation: "Abuja (hotel pickup)",
    totalCapacity: 10,
    remainingCapacity: 10,
    cancellationPolicy: "Free cancellation up to 72 hours before departure.",
    description: "Discover Nigeria's premier game reserve — a 2,244 sq km protected wilderness in Bauchi State home to one of the largest elephant populations in West Africa, plus hippos, baboons, warthogs, and over 350 bird species. After morning game drives, cool off in Wikki Warm Springs — crystal-clear 31°C waters that bubble naturally from beneath the savannah. This is safari Nigeria: raw, unspoiled, and genuinely wild.",
    highlights: [
      "4×4 game drives searching for elephants, buffalo, and baboons in miombo woodland",
      "Wikki Warm Springs — crystal-clear natural pool at a constant 31°C, perfect for swimming",
      "Hippo pool observation at close range along the Gaji River",
      "Baboon and warthog sightings guaranteed around the lodge grounds",
      "350+ bird species including grey crowned cranes and martial eagles",
      "Optional night spotlight drive — chance to see civets, genets, and hyenas",
    ],
    inclusions: [
      "Return private AC transport from Abuja",
      "3 nights accommodation at Wikki Tourist Camp (double rooms)",
      "Park entrance fees (4 days)",
      "4 guided game drives in 4×4 vehicle",
      "1 hippo trail ranger walk",
      "1 guided birdwatching walk",
      "All meals (3 breakfasts, 3 lunches, 3 dinners)",
      "Wikki Warm Springs access",
      "Professional safari guide throughout",
    ],
    exclusions: [
      "Domestic flights to Bauchi (optional upgrade)",
      "Night spotlight drive (optional, NGN 8,000 per vehicle)",
      "International flights",
      "Travel insurance",
      "Alcoholic beverages",
    ],
    itinerary: [
      {
        day: 1,
        title: "Abuja to Yankari — Arrival Safari",
        description: "Depart Abuja by private vehicle (4.5 hr drive) to Yankari. Check in to Wikki Tourist Camp. Late afternoon game drive targeting elephants at the watering holes.",
        activities: [
          { activity: "Depart Abuja — private AC vehicle (4.5 hr drive)" },
          { activity: "Check in to Wikki Tourist Camp inside the park" },
          { activity: "Late afternoon game drive — elephants at the watering holes" },
          { activity: "Sunset dip in Wikki Warm Springs" },
          { activity: "Dinner at camp restaurant" },
        ],
      },
      {
        day: 2,
        title: "Full Day Safari — Morning & Evening Drives",
        description: "Pre-dawn walking safari at 5:30am when elephants are most active. Mid-morning swim at Wikki Warm Springs. Afternoon hippo trail walk and evening game drive.",
        activities: [
          { activity: "Pre-dawn 5:30am game drive — elephants most active at dawn" },
          { activity: "Breakfast at camp" },
          { activity: "Mid-morning swim at Wikki Warm Springs" },
          { activity: "Afternoon hippo trail walk with armed ranger" },
          { activity: "Sunset 4×4 game drive" },
          { activity: "Optional night spotlight drive (extra cost)" },
        ],
      },
      {
        day: 3,
        title: "Yankari Museum, Gaji River & Bird Walk",
        description: "Morning at Yankari Museum. Guided birdwatching walk along the Gaji River. Afternoon game drive in a different sector of the park.",
        activities: [
          { activity: "Morning visit to Yankari Museum — cultural and wildlife exhibits" },
          { activity: "Guided birdwatching walk along the Gaji River (3 hrs)" },
          { activity: "Packed lunch riverside" },
          { activity: "Afternoon game drive — new sector of the park" },
          { activity: "Evening cultural performance at camp" },
        ],
      },
      {
        day: 4,
        title: "Final Dawn Drive & Departure",
        description: "Final 5:30am game drive then breakfast and departure back to Abuja.",
        activities: [
          { activity: "Final 5:30am game drive" },
          { activity: "Breakfast and check out" },
          { activity: "Depart for Abuja" },
        ],
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1560118386-f35cf6a0791d?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1577900190299-7316c32fe85f?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1631452164937-4f6468db832a?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1716998462026-66dbe5c97af3?w=1200&q=80&auto=format&fit=crop",
    ],
  },

  {
    title: "Kingdom of Benin — Bronze, Brass & Royal Legacy",
    country: "nigeria",
    destinationName: "Benin City",
    destinationRegion: "Edo State",
    destinationCountry: "Nigeria",
    durationDays: 3,
    basePrice: 145,
    displayCurrency: "USD",
    tourType: "multi_day",
    category: "leisure",
    difficulty: "easy",
    rating: 4.8,
    reviewCount: 83,
    featured: true,
    bestFor: ["History enthusiasts", "Art collectors", "Diaspora visitors", "Academics", "Culture lovers"],
    tags: ["Heritage", "History", "Art", "Royalty", "Bronze", "UNESCO", "Culture"],
    languages: ["English"],
    pickupIncluded: true,
    pickupLocation: "Lagos (Murtala Muhammed Airport)",
    totalCapacity: 12,
    remainingCapacity: 12,
    cancellationPolicy: "Free cancellation up to 48 hours before departure.",
    description: "Explore one of Africa's greatest pre-colonial civilizations in Benin City — the seat of the ancient Benin Kingdom whose bronze-casting tradition produced some of the most technically accomplished metalwork in human history. Walk streets where royal bronze-casters still practice their 800-year-old craft, visit the Oba's Palace compound, and trace the ancient Benin Moat — the largest earthwork structure ever built by humans.",
    highlights: [
      "Oba's Palace — the living ceremonial seat of the Oba of Benin, one of Africa's oldest continuous monarchies",
      "Igun Street Bronze Casting Quarter — UNESCO-designated street where hereditary casters work as they have for 800 years",
      "National Museum of Benin — original Benin Bronzes, ivory carvings, and royal regalia",
      "Benin Moat (Iya) — the largest man-made earthwork in the world (over 16,000 km of ramparts)",
      "Chief's Compound visit — insight into Benin's feudal hierarchy and living traditions",
      "Igue Festival — spectacular royal spiritual renewal ceremony (December, seasonal)",
    ],
    inclusions: [
      "Return domestic flights Lagos–Benin City",
      "Private AC transport within Benin City",
      "Licensed cultural guide specializing in Benin Kingdom history (3 days)",
      "All entrance fees (National Museum, Oba's Palace, Igun Street)",
      "2 nights accommodation (3-star hotel, Benin City)",
      "Day 1 dinner, Day 2 breakfast & dinner, Day 3 breakfast and lunch",
      "Bottled water throughout",
    ],
    exclusions: [
      "International flights",
      "Personal purchases (bronze sculptures, carvings)",
      "Travel insurance",
      "Commissioned bronze pieces",
    ],
    itinerary: [
      {
        day: 1,
        title: "Lagos to Benin City — Royal Arrival",
        description: "Fly from Lagos to Benin City (50 min). Afternoon visit to National Museum and Igun Street bronze casting quarter.",
        activities: [
          { activity: "Fly Lagos to Benin City (50 min domestic flight)" },
          { activity: "Check in to hotel in Benin City" },
          { activity: "Afternoon visit to National Museum of Benin — Benin Bronzes, ivory carvings" },
          { activity: "Walk to Igun Street — watch bronze casters using the lost-wax technique" },
          { activity: "Dinner — banga soup and starch, traditional Benin cuisine" },
        ],
      },
      {
        day: 2,
        title: "Oba's Palace, Benin Moat & Chiefs' Quarter",
        description: "Guided tour of the Oba's Palace compound and museum. Visit sections of the ancient Benin Moat. Walk through the traditional Chief's compound.",
        activities: [
          { activity: "Morning guided tour of the Oba's Palace compound" },
          { activity: "Palace museum — ceremonial objects, royal portraits, leopard motifs" },
          { activity: "Drive to see the Benin Moat sections still visible in the city" },
          { activity: "Visit a traditional Chief's compound with local guide" },
          { activity: "Afternoon souvenir shopping — bronze sculptures, woodcarvings" },
          { activity: "Evening cultural talk by local historian" },
        ],
      },
      {
        day: 3,
        title: "Artisan Quarter, Craft Market & Departure",
        description: "Return to Igun Street with opportunity to commission a personalised bronze piece. Visit Ewedo Carving Quarter then transfer to the airport.",
        activities: [
          { activity: "Return to Igun Street — commission a personalised bronze piece" },
          { activity: "Visit Ewedo Carving Quarter for woodwork and mask-making" },
          { activity: "Local market for fabric and traditional Benin garments" },
          { activity: "Lunch at local restaurant" },
          { activity: "Transfer to Benin Airport for return flight" },
        ],
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1614005157364-67894d3dc531?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1615027212409-2628cc0cc11a?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80&auto=format&fit=crop",
    ],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // TOGO
  // ════════════════════════════════════════════════════════════════════════════

  {
    title: "Lomé Spirit & Fetish — The World's Largest Voodoo Market",
    country: "togo",
    destinationName: "Lomé",
    destinationRegion: "Maritime Region",
    destinationCountry: "Togo",
    durationDays: 1,
    basePrice: 95,
    displayCurrency: "USD",
    tourType: "day_tour",
    category: "leisure",
    difficulty: "easy",
    rating: 4.6,
    reviewCount: 87,
    featured: true,
    bestFor: ["Solo travelers", "Couples", "Cultural enthusiasts", "Photographers"],
    tags: ["Culture", "Heritage", "Spiritual", "Markets", "Voodoo", "Photography"],
    languages: ["English", "French"],
    pickupIncluded: true,
    pickupLocation: "Lomé hotel pickup",
    totalCapacity: 16,
    remainingCapacity: 16,
    cancellationPolicy: "Free cancellation up to 24 hours before departure.",
    description: "Plunge into the spiritual heartbeat of West Africa at the Akodessawa Fetish Market — the world's largest voodoo market — where traditional healers, animist priests, and fetish merchants trade in ancient power. Beyond the market, discover Lomé's sacred cathedral, the Nana Benz traders of the Grand Marché, and colonial waterfront boulevards. One of the most extraordinary cultural encounters on the continent.",
    highlights: [
      "Walk the stalls of Akodessawa — the world's largest voodoo fetish market — surrounded by skulls, dried herbs, and ancestral charms",
      "Consult a fetish priest (bokono) for a traditional divination or blessing ritual",
      "Explore the Grand Marché de Lomé and meet the legendary Nana Benz cloth traders",
      "Visit the Sacred Heart Cathedral, a striking colonial landmark at the city centre",
      "Stroll the palm-lined Boulevard du Mono along the Gulf of Guinea",
      "Discover the Place de l'Indépendance and the city's lively artisan quarter",
    ],
    inclusions: [
      "Round-trip hotel transfers in Lomé",
      "Licensed English-speaking local guide",
      "All market and site entry fees",
      "Traditional Togolese lunch",
      "Bottled water throughout",
    ],
    exclusions: [
      "International flights",
      "Visa fees",
      "Personal purchases at the market",
      "Gratuities",
    ],
    itinerary: [
      {
        day: 1,
        title: "Lomé: Markets, Spirits & the Waterfront",
        description: "Morning visit to Akodessawa Fetish Market with a licensed guide. Grand Marché walk with the Nana Benz traders. Traditional Togolese lunch. Afternoon visit to the Sacred Heart Cathedral and Boulevard du Mono.",
        activities: [
          { activity: "Morning pickup and transfer to Akodessawa Fetish Market" },
          { activity: "Guided tour of the world's largest voodoo market" },
          { activity: "Optional consultation with a traditional healer" },
          { activity: "Walk through Grand Marché de Lomé — Nana Benz cloth stalls" },
          { activity: "Togolese lunch at local restaurant" },
          { activity: "Visit Sacred Heart Cathedral and Boulevard du Mono" },
          { activity: "Place de l'Indépendance before hotel drop-off" },
        ],
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1734255026082-82fdc81991f0?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1614005157364-67894d3dc531?w=1200&q=80&auto=format&fit=crop",
    ],
  },

  {
    title: "Kpalimé Highlands & Butterfly Safari — Togo's Green Escape",
    country: "togo",
    destinationName: "Kpalimé",
    destinationRegion: "Plateaux Region",
    destinationCountry: "Togo",
    durationDays: 2,
    basePrice: 210,
    displayCurrency: "USD",
    tourType: "multi_day",
    category: "ekolure",
    difficulty: "moderate",
    rating: 4.7,
    reviewCount: 63,
    bestFor: ["Nature lovers", "Hikers", "Solo travelers", "Couples", "Birdwatchers"],
    tags: ["Nature", "Hiking", "Wildlife", "Butterflies", "Waterfalls", "Culture"],
    languages: ["English", "French"],
    pickupIncluded: true,
    pickupLocation: "Lomé hotel pickup",
    totalCapacity: 12,
    remainingCapacity: 12,
    cancellationPolicy: "Free cancellation up to 48 hours before departure.",
    description: "Escape Lomé's heat into the lush Plateaux region, where rolling highlands, misty coffee plantations, and cascading waterfalls await. Kpalimé sits at the foot of Mount Agou — Togo's highest peak — and the slopes of Mount Kloto harbour over 500 species of butterfly in dense rainforest. This two-day tour blends summit hiking, waterfall swimming, craft-market browsing, and the spectacular Akpesse traditional dance performance.",
    highlights: [
      "Hike to the summit of Mount Agou (986m) — Togo's highest peak — through villages and terraced plantations",
      "Butterfly safari on Mount Kloto through dense forest hosting 500+ butterfly species",
      "Swim in the natural pool at the Cascade de Kpimé waterfall",
      "Visit a batik and macramé craft centre in Kpalimé town",
      "Watch the Akpesse traditional folkdance performed by local villagers",
      "Drive through coffee and cocoa plantation country on the Plateaux scenic route",
    ],
    inclusions: [
      "Round-trip transport Lomé–Kpalimé (air-conditioned vehicle)",
      "Licensed English/French-speaking guide throughout",
      "1 night guesthouse accommodation",
      "All meals: 1 dinner, 2 breakfasts, 1 lunch",
      "Waterfall and site entry fees",
      "Bottled water and trail snacks",
    ],
    exclusions: [
      "International flights",
      "Travel insurance",
      "Personal purchases at craft market",
      "Gratuities",
    ],
    itinerary: [
      {
        day: 1,
        title: "Lomé to Kpalimé — Butterfly Safari & Cascade",
        description: "Drive through cocoa country to Kpalimé (2.5 hours). Butterfly safari trail on Mount Kloto. Afternoon hike to the Cascade de Kpimé for a swim in the natural pool.",
        activities: [
          { activity: "Depart Lomé at 7am — drive through Tsévié and the cocoa belt (2.5 hrs)" },
          { activity: "Butterfly safari trail on Mount Kloto — 500+ species" },
          { activity: "Afternoon hike to Cascade de Kpimé" },
          { activity: "Swim in the natural pool beneath the falls" },
          { activity: "Check in at guesthouse in Kpalimé — dinner with Togolese specialities" },
        ],
      },
      {
        day: 2,
        title: "Mount Agou Summit Hike & Craft Market",
        description: "Early morning trek to the summit of Mount Agou through coffee plantations with panoramic views. Visit the Kpalimé artisan craft centre. Watch an Akpesse dance performance before returning to Lomé.",
        activities: [
          { activity: "Early morning drive to base of Mount Agou" },
          { activity: "Trek to summit through mountain villages and coffee plantations" },
          { activity: "Panoramic views over Ghana and Benin on clear days" },
          { activity: "Visit Kpalimé artisan craft centre — batik cloth, leather, ceramics" },
          { activity: "Akpesse traditional dance performance in a local village" },
          { activity: "Scenic 2.5-hour drive back to Lomé" },
        ],
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1678714001094-ba90abd57fec?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1519830103773-4bdc5166a0db?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1523952578875-e6bb18b26645?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1464419014442-769c523d575b?w=1200&q=80&auto=format&fit=crop",
    ],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // CÔTE D'IVOIRE
  // ════════════════════════════════════════════════════════════════════════════

  {
    title: "Abidjan Rhythm & Lagoon — City of Contrasts Tour",
    country: "côte d'ivoire",
    destinationName: "Abidjan",
    destinationRegion: "Lagunes District",
    destinationCountry: "Côte d'Ivoire",
    durationDays: 1,
    basePrice: 124,
    displayCurrency: "USD",
    tourType: "day_tour",
    category: "leisure",
    difficulty: "easy",
    rating: 4.5,
    reviewCount: 112,
    bestFor: ["Families", "Couples", "Business travellers", "First-time visitors", "Solo travelers"],
    tags: ["Culture", "Heritage", "Nature", "Markets", "Urban", "Art", "Food"],
    languages: ["English", "French"],
    pickupIncluded: true,
    pickupLocation: "Abidjan hotel pickup",
    totalCapacity: 12,
    remainingCapacity: 12,
    cancellationPolicy: "Free cancellation up to 24 hours before departure.",
    description: "Often called the 'Paris of West Africa', Abidjan is a skyline city wrapped around the Ébrié Lagoon, and this full-day tour reveals both its cosmopolitan energy and its soulful neighbourhoods. Cross the lagoon by traditional pirogue, explore the mask-filled halls of the Musée des Civilisations, wander the artisan village at CAVA, and walk the rainforest trails of Banco National Park.",
    highlights: [
      "Pirogue ride across the Ébrié Lagoon with views of Abidjan's towering Plateau skyline",
      "Musée des Civilisations de Côte d'Ivoire — 20,000 wooden masks and terracotta statues",
      "Centre Artisanal de la Ville (CAVA) for Korhogo cloth, bronze jewellery, and batiks",
      "Banco National Park — West Africa's largest urban forest reserve",
      "Plateau district modernist architecture and the Mosquée du Plateau",
      "Bustling street life and open-air restaurants of Treichville",
    ],
    inclusions: [
      "Hotel pickup and drop-off in Abidjan",
      "English-speaking licensed guide",
      "Pirogue lagoon crossing",
      "Museum and National Park entrance fees",
      "Ivorian lunch at local maquis",
      "Air-conditioned vehicle throughout",
      "Bottled water",
    ],
    exclusions: [
      "International flights",
      "Travel insurance",
      "Personal shopping at CAVA",
      "Gratuities",
    ],
    itinerary: [
      {
        day: 1,
        title: "Abidjan: Lagoon Crossing, Museums & Rainforest",
        description: "Traditional pirogue crossing of the Ébrié Lagoon. Plateau district walk past key landmarks. Musée des Civilisations. Ivorian lunch. CAVA artisan village. Banco National Park rainforest walk.",
        activities: [
          { activity: "Morning pickup and drive to Treichville wharf" },
          { activity: "Traditional pirogue crossing of the Ébrié Lagoon" },
          { activity: "Plateau district walk — Mosquée du Plateau, St. Paul's Cathedral" },
          { activity: "Visit Musée des Civilisations — 20,000 artefacts from 62 ethnic groups" },
          { activity: "Lunch at a local maquis restaurant" },
          { activity: "Browse CAVA artisan village — Korhogo cloth, bronze jewellery" },
          { activity: "Guided walk through Banco National Park's rainforest" },
        ],
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1648770664367-54d43741edf1?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1552709586-d1aefe5d04b4?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1591471682965-06e508dd6a32?w=1200&q=80&auto=format&fit=crop",
    ],
  },

  {
    title: "Yamoussoukro & the Basilica of Peace — Coffee Country Drive",
    country: "côte d'ivoire",
    destinationName: "Yamoussoukro",
    destinationRegion: "Bélier Region",
    destinationCountry: "Côte d'Ivoire",
    durationDays: 2,
    basePrice: 285,
    displayCurrency: "USD",
    tourType: "multi_day",
    category: "leisure",
    difficulty: "easy",
    rating: 4.8,
    reviewCount: 94,
    featured: true,
    bestFor: ["Couples", "Families", "History enthusiasts", "Architecture lovers"],
    tags: ["Heritage", "Architecture", "Culture", "Food", "Nature", "History"],
    languages: ["English", "French"],
    pickupIncluded: true,
    pickupLocation: "Abidjan hotel pickup",
    totalCapacity: 10,
    remainingCapacity: 10,
    cancellationPolicy: "Free cancellation up to 48 hours before departure.",
    description: "Journey inland from Abidjan through the heart of the world's top cocoa-producing nation to Yamoussoukro — home to the Basilica of Our Lady of Peace, the largest church on Earth. Stand inside the gilded dome that dwarfs St. Peter's in Rome, feed sacred Nile crocodiles at the Presidential Palace moat, and explore the ghost-town grandeur of Africa's most surprising capital.",
    highlights: [
      "Tour the Basilica of Our Lady of Peace — officially the world's largest church, seating 18,000 beneath 7,000m² of stained glass",
      "Feed sacred Nile crocodiles at the Presidential Palace crocodile lake",
      "Drive through the world's largest cocoa-producing region with a plantation stop",
      "Visit the Félix Houphouët-Boigny Foundation for Peace",
      "Explore Yamoussoukro's eerily grand avenues — a capital built for millions but home to thousands",
      "Taste freshly processed Ivorian arabica coffee at a family-run cooperative",
    ],
    inclusions: [
      "Round-trip transport Abidjan–Yamoussoukro (air-conditioned vehicle)",
      "English/French-speaking licensed guide",
      "1 night hotel accommodation in Yamoussoukro",
      "Basilica and Presidential Palace entry fees",
      "Meals: 1 dinner, 2 breakfasts, 1 lunch",
      "Plantation/cooperative visit",
      "Bottled water throughout",
    ],
    exclusions: [
      "International flights",
      "Travel insurance",
      "Personal souvenirs",
      "Gratuities",
    ],
    itinerary: [
      {
        day: 1,
        title: "Abidjan to Yamoussoukro — Basilica & Sacred Crocodiles",
        description: "Depart Abidjan at 6:30am. Arrive Yamoussoukro by 9:30am. Guided visit to the Basilica of Our Lady of Peace. Lunch. Afternoon: Presidential Palace grounds and the sacred crocodile lake.",
        activities: [
          { activity: "Depart Abidjan at 6:30am on the A3 highway through cocoa country" },
          { activity: "Arrive Yamoussoukro — guided visit to the Basilica of Our Lady of Peace" },
          { activity: "Lunch near the city centre" },
          { activity: "Guided visit to Presidential Palace — sacred crocodile lake" },
          { activity: "Crocodiles fed on live chickens — an unmissable ritual" },
          { activity: "Visit Houphouët-Boigny Foundation; check in and dinner" },
        ],
      },
      {
        day: 2,
        title: "Coffee Plantation Visit & Return to Abidjan",
        description: "Morning at a local coffee cooperative — full process from bean to cup. Return to Abidjan with a roadside Baoulé craft stop.",
        activities: [
          { activity: "Morning visit to coffee cooperative — bean to cup demonstration" },
          { activity: "Take home freshly roasted coffee" },
          { activity: "Drive back toward Abidjan — stop at roadside Baoulé craft market" },
          { activity: "Arrive Abidjan mid-afternoon" },
        ],
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1648770664367-54d43741edf1?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1601221656510-e23d747fec7c?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1591471682965-06e508dd6a32?w=1200&q=80&auto=format&fit=crop",
    ],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // SENEGAL
  // ════════════════════════════════════════════════════════════════════════════

  {
    title: "Dakar & Gorée Island — Gateway to Memory",
    country: "senegal",
    destinationName: "Dakar",
    destinationRegion: "Dakar Region",
    destinationCountry: "Senegal",
    durationDays: 1,
    basePrice: 160,
    displayCurrency: "USD",
    tourType: "day_tour",
    category: "leisure",
    difficulty: "easy",
    rating: 4.8,
    reviewCount: 241,
    featured: true,
    bestFor: ["Couples", "Solo travelers", "Families", "History enthusiasts", "Educational groups"],
    tags: ["Heritage", "History", "Culture", "UNESCO", "Island", "Architecture"],
    languages: ["English", "French", "Wolof"],
    pickupIncluded: true,
    pickupLocation: "Dakar hotel pickup",
    totalCapacity: 16,
    remainingCapacity: 16,
    cancellationPolicy: "Free cancellation up to 24 hours before departure.",
    description: "This moving full-day experience combines Dakar's dynamic cityscape with a ferry crossing to Gorée Island — a UNESCO World Heritage Site that served as one of the Atlantic's principal slave-trading posts for three centuries. Stand at the Gate of No Return in the House of Slaves, walk the rose-pink cobblestone alleys, then return to explore the Monument of African Renaissance and Dakar's vivid street life.",
    highlights: [
      "Ferry ride from Dakar's port to Gorée Island (25 minutes) across the azure Atlantic",
      "Guided visit to the House of Slaves (Maison des Esclaves) and the Gate of No Return",
      "Explore Gorée's colourful colonial streets and hilltop Fort d'Estrées",
      "Visit the Monument of African Renaissance (52m bronze statue) overlooking Dakar",
      "IFAN Museum of African Arts and the vibrant Sandaga market",
      "Sunset views from the Almadies Peninsula — Africa's westernmost point",
    ],
    inclusions: [
      "Hotel pickup and drop-off in Dakar",
      "Air-conditioned vehicle and English-speaking guide",
      "Round-trip Gorée Island ferry tickets",
      "House of Slaves entry fee",
      "Monument of African Renaissance entry",
      "Traditional Senegalese lunch on Gorée Island",
      "Bottled water throughout",
    ],
    exclusions: [
      "International flights",
      "Travel insurance",
      "Personal shopping",
      "Gratuities",
    ],
    itinerary: [
      {
        day: 1,
        title: "Dakar City Highlights & Gorée Island Heritage",
        description: "Monument of African Renaissance and IFAN Museum in the morning. Ferry to Gorée Island for the House of Slaves and Gate of No Return. Senegalese lunch on Gorée. Return ferry and afternoon at Sandaga market and Almadies Peninsula.",
        activities: [
          { activity: "Morning pickup — drive to Monument of African Renaissance" },
          { activity: "Panoramic views over Dakar from the monument" },
          { activity: "IFAN Museum of African Arts" },
          { activity: "Ferry terminal — 25-minute crossing to Gorée Island" },
          { activity: "Guided visit to House of Slaves and Gate of No Return" },
          { activity: "Free time on Gorée — streets, artists, galleries" },
          { activity: "Senegalese lunch on the island (thiéboudienne or yassa)" },
          { activity: "Return ferry to Dakar — Sandaga market and Almadies Peninsula" },
        ],
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1570651385727-84ef21168d93?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1528047705243-ebb19baf436f?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80&auto=format&fit=crop",
    ],
  },

  {
    title: "Pink Lake & Cap Skirring — Dunes, Salt & Atlantic Sands",
    country: "senegal",
    destinationName: "Dakar",
    destinationRegion: "Dakar Region",
    destinationCountry: "Senegal",
    durationDays: 3,
    basePrice: 420,
    displayCurrency: "USD",
    tourType: "multi_day",
    category: "leisure",
    difficulty: "easy",
    rating: 4.7,
    reviewCount: 178,
    featured: true,
    bestFor: ["Couples", "Families", "Photographers", "Beach lovers", "Adventurers"],
    tags: ["Beach", "Nature", "Culture", "Adventure", "Photography", "Unique Landscapes", "Coastal"],
    languages: ["English", "French", "Wolof"],
    pickupIncluded: true,
    pickupLocation: "Dakar hotel pickup",
    totalCapacity: 10,
    remainingCapacity: 10,
    cancellationPolicy: "Free cancellation up to 48 hours before departure.",
    description: "This three-day odyssey moves from the hypnotic pink waters of Lac Rose (Lake Retba) — made famous by the Paris-Dakar rally — south through Casamance forests to the white-sand crescents of Cap Skirring, widely regarded as West Africa's finest beach. Ride camels over terracotta dunes, watch salt harvesters, and discover the Diola culture of Casamance's fishing villages.",
    highlights: [
      "Float in the hypersaline pink waters of Lac Rose, tinted by Dunaliella salina algae — saltier than the Dead Sea",
      "Watch traditional salt harvesters wade the lake balancing heavy baskets",
      "Camel ride and optional quad-bike ride over the terracotta dunes at sunset",
      "Cap Skirring: 90km of golden Atlantic beach — swim, kayak, and windsurf",
      "Visit a Diola fishing village: watch pirogues land the morning catch",
      "Casamance scenic drive through mango forests and bamboo groves",
    ],
    inclusions: [
      "Return transport Dakar–Cap Skirring (air-conditioned vehicle)",
      "2 nights accommodation (1 eco-lodge Lac Rose, 1 beach lodge Cap Skirring)",
      "All meals: 2 dinners, 3 breakfasts, 1 lunch",
      "English/French-speaking guide throughout",
      "Lac Rose pirogue ride and salt harvester visit",
      "Camel ride at Lac Rose",
      "Diola village cultural walk at Cap Skirring",
      "Bottled water throughout",
    ],
    exclusions: [
      "International flights",
      "Travel insurance",
      "Quad-bike rental (optional)",
      "Water sports equipment hire",
      "Gratuities",
    ],
    itinerary: [
      {
        day: 1,
        title: "Dakar to Lac Rose — Pink Waters & Dune Adventure",
        description: "Drive 30km northeast to Lac Rose. Guided tour of the lake and salt harvesting operation. Optional float in the buoyant pink water. Afternoon camel ride and optional quad-bike dune safari at sunset.",
        activities: [
          { activity: "Depart Dakar at 9am — 30km northeast to Lac Rose" },
          { activity: "Guided tour and boat ride across the shallows" },
          { activity: "Visit the salt harvesting operation" },
          { activity: "Optional float in the buoyant pink water" },
          { activity: "Camel ride and optional quad-bike dune safari at sunset" },
          { activity: "Dinner and overnight at eco-lodge near the lake" },
        ],
      },
      {
        day: 2,
        title: "Road South to Casamance — Forest & Culture Drive",
        description: "Drive south through Casamance route passing Diola villages and bamboo-lined roads. Arrive Cap Skirring by midday. Afternoon beach and fishing village visit.",
        activities: [
          { activity: "Early breakfast and depart south — Casamance route" },
          { activity: "Drive through Kabrousse forest and sacred Diola villages" },
          { activity: "Arrive Cap Skirring by midday" },
          { activity: "Afternoon at leisure on the beach — swimming, kayak hire" },
          { activity: "Walk to fishing village — watch the catch come in" },
          { activity: "Sunset dinner at seafront restaurant — Casamançais grilled fish" },
        ],
      },
      {
        day: 3,
        title: "Cap Skirring Diola Village & Return to Dakar",
        description: "Morning walk through the Diola village with a local guide — traditional houses, sacred kapok trees, and rice paddies. Optional sea kayak through mangrove channels. Return to Dakar.",
        activities: [
          { activity: "Morning walk through Diola village — impluvium houses, sacred kapok trees" },
          { activity: "Optional early-morning sea kayak through mangrove channels" },
          { activity: "Late morning transfer to Ziguinchor or road back to Dakar" },
          { activity: "Arrive Dakar by early evening" },
        ],
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1517522072116-71c8b8182c07?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1570651385727-84ef21168d93?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1528047705243-ebb19baf436f?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1721011372247-2da3408bb076?w=1200&q=80&auto=format&fit=crop",
    ],
  },

  {
    title: "Sine-Saloum Delta — Mangroves, Pirogues & Serer Villages",
    country: "senegal",
    destinationName: "Dakar",
    destinationRegion: "Dakar Region",
    destinationCountry: "Senegal",
    durationDays: 5,
    basePrice: 750,
    displayCurrency: "USD",
    tourType: "multi_day",
    category: "ekolure",
    difficulty: "easy",
    rating: 4.9,
    reviewCount: 156,
    featured: true,
    bestFor: ["Nature lovers", "Birdwatchers", "Couples", "Solo travelers", "Eco-conscious travelers", "Photographers"],
    tags: ["Eco-Tourism", "Nature", "Birdwatching", "Culture", "Heritage", "Mangroves", "UNESCO"],
    languages: ["English", "French", "Wolof"],
    pickupIncluded: true,
    pickupLocation: "Dakar hotel pickup",
    totalCapacity: 10,
    remainingCapacity: 10,
    cancellationPolicy: "Free cancellation up to 72 hours before departure.",
    description: "The Sine-Saloum Delta is one of West Africa's most breathtaking landscapes — a UNESCO Biosphere Reserve where labyrinthine waterways thread through ancient mangroves, shell-island villages, and habitats for 400+ bird species. For five days you travel by traditional pirogue, sleeping in eco-lodges on stilts, eating fresh-caught fish under the stars, and learning the ancestral ways of the Serer fishing communities.",
    highlights: [
      "Navigate the UNESCO-listed Saloum Delta by traditional pirogue through cathedral-like mangrove tunnels",
      "Visit shell islands — islands literally built from ancient oyster shells over millennia",
      "Sunrise birdwatching: pink flamingos, white pelicans, African fish eagles, spoonbills, and 400+ species",
      "Stay in eco-lodges perched on the delta's edge, dining on the day's catch",
      "Walk isolated Serer fishing villages accessible only by water",
      "Optional traditional fishing by dugout at dawn and evening drum-and-music sessions",
    ],
    inclusions: [
      "Return air-conditioned transport Dakar–Sine-Saloum",
      "4 nights eco-lodge accommodation (full board — all meals included)",
      "All meals throughout including fresh fish and locally sourced produce",
      "Daily pirogue navigation with fuel and specialist Serer guide",
      "English-speaking specialist guide",
      "All village, birdwatching site, and heritage entry fees",
    ],
    exclusions: [
      "International flights",
      "Personal travel insurance",
      "Alcoholic beverages",
      "Optional activities (kayak rental, massage)",
      "Gratuities",
    ],
    itinerary: [
      {
        day: 1,
        title: "Dakar to Joal-Fadiouth & Delta Arrival",
        description: "Depart Dakar by AC vehicle (3.5 hours south). Stop at Joal-Fadiouth — birthplace of Léopold Sédar Senghor — and walk the shell-sand causeway to the island. Continue to the Saloum Delta eco-lodge. Sunset pirogue orientation.",
        activities: [
          { activity: "Depart Dakar at 7am (3.5 hours south)" },
          { activity: "Stop at Joal-Fadiouth — shell-sand causeway to the island" },
          { activity: "Visit historic Christian-Muslim cemetery built on shells" },
          { activity: "Continue to Saloum Delta eco-lodge" },
          { activity: "Sunset pirogue orientation along the bolong channel" },
          { activity: "Welcome dinner at eco-lodge" },
        ],
      },
      {
        day: 2,
        title: "Full-Day Pirogue Deep Dive — Mangroves, Islands & Villages",
        description: "Full day by pirogue navigating the labyrinthine bolongs through mangrove forests to isolated villages. Picnic lunch on a shell island. Ancient midden mound exploration.",
        activities: [
          { activity: "Depart by pirogue at 8am with Serer guide" },
          { activity: "Navigate the bolongs through mangrove forests" },
          { activity: "Visit isolated villages of Falia, Djirnack, and Faoye" },
          { activity: "Picnic lunch on a shell island" },
          { activity: "Explore the ancient midden mounds" },
          { activity: "Return to eco-lodge — fresh fish dinner" },
        ],
      },
      {
        day: 3,
        title: "Mar Lodj Island — Baobabs, Birdwatching & Ocean Swim",
        description: "Pirogue to Mar Lodj Island, the delta's most authentic inhabited island. Village walk under enormous baobabs. Atlantic-facing birdwatching (flamingos and pelicans). Evening kora and balafon music performance.",
        activities: [
          { activity: "Dawn pirogue departure to Mar Lodj Island" },
          { activity: "Village walk with local guide — enormous baobab trees" },
          { activity: "Birdwatching session — flamingos and pelicans at low tide" },
          { activity: "Ocean swimming and relaxation on the sandbar beach" },
          { activity: "Lunch with a local Serer family" },
          { activity: "Evening balafon and kora music performance at the eco-lodge" },
        ],
      },
      {
        day: 4,
        title: "Dawn Fishing, Shell Mounds & Kayaking",
        description: "Optional traditional fishing by dugout at 5:30am. Shell mound archaeological sites. Afternoon kayaking through quieter bolongs. Sunset pirogue through golden mangroves.",
        activities: [
          { activity: "Optional 5:30am traditional fishing by dugout canoe" },
          { activity: "Breakfast back at lodge" },
          { activity: "Walk to ancient oyster-shell mound archaeological sites" },
          { activity: "Afternoon kayak through quieter bolongs" },
          { activity: "Optional guided bird count walk" },
          { activity: "Sunset pirogue through the golden mangroves" },
        ],
      },
      {
        day: 5,
        title: "Final Dawn Birding & Return to Dakar",
        description: "Optional pre-dawn birdwatching walk (best November–February for migratory species). Checkout after breakfast. Return to Dakar with a possible Saly or Mbour craft market stop.",
        activities: [
          { activity: "Optional pre-dawn birdwatching walk" },
          { activity: "Checkout after breakfast" },
          { activity: "Return journey to Dakar with optional craft market stop" },
          { activity: "Arrive Dakar mid-afternoon" },
        ],
      },
    ],
    images: [
      "https://images.unsplash.com/photo-1648504735627-6af97e8337a9?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1517522072116-71c8b8182c07?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1570651385727-84ef21168d93?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1528047705243-ebb19baf436f?w=1200&q=80&auto=format&fit=crop",
    ],
  },
];

// ── Seed runner ────────────────────────────────────────────────────────────────
async function seed() {
  await mongoose.connect(MONGO_URI);
  console.log("Connected to MongoDB.\n");

  let Destination;
  try { Destination = mongoose.model("Destination"); }
  catch (_) { Destination = mongoose.model("Destination", DestinationSchema, "destinations"); }

  let TourPackage;
  try { TourPackage = mongoose.model("TourPackage"); }
  catch (_) { TourPackage = mongoose.model("TourPackage", TourPackageSchema, "tourpackages"); }

  async function findOrCreateDestination(name, country, region, coverImage) {
    let dest = await Destination.findOne({ name });
    if (dest) return dest;
    const destSlug = slugify(name, { lower: true, strict: true });
    dest = await Destination.create({ name, slug: destSlug, country, region, coverImage, isActive: true });
    console.log(`  DEST NEW  ${name} (${country})`);
    return dest;
  }

  let inserted = 0;
  let skipped = 0;

  for (const tour of tours) {
    const slug = slugify(tour.title, { lower: true, strict: true });
    const existing = await TourPackage.findOne({ slug });
    if (existing) {
      console.log(`  SKIP  ${tour.title}`);
      skipped++;
      continue;
    }

    const dest = await findOrCreateDestination(
      tour.destinationName,
      tour.destinationCountry,
      tour.destinationRegion,
      tour.images[0]
    );

    const { destinationName, destinationRegion, destinationCountry, ...tourData } = tour;

    await TourPackage.create({
      ...tourData,
      slug,
      destinationId: dest._id,
      coverImage: tourData.images[0],
      heroMainImage: tourData.images[0],
      heroImages: tourData.images.slice(0, 3),
    });

    console.log(`  OK    ${tour.title} (${tour.country})`);
    inserted++;
  }

  console.log(`\nDone. Inserted: ${inserted}, Skipped: ${skipped}`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("Seed failed:", err.message);
  process.exit(1);
});
